.SUFFIXES: .ac

all: Makefile
	make -j

Makefile: configure
	./configure CC=colorgcc

configure: configure.ac
	mkdir -p build-aux
	touch build-aux/config.rpath
	aclocal -I m4
	autoheader
	libtoolize --force || glibtoolize --force
	automake -a --foreign
	autoconf
