VERSION=$(shell grep AC_INIT configure.ac | sed -e "s/.*\[\([0-9\.]*\)\].*/\1/")

# https://wiki.debian.org/IntroDebianPackaging
# https://en.opensuse.org/openSUSE:Build_Service_Tutorial
package::
	mkdir -p pkg
	cp aiscm-$(VERSION).tar.gz pkg/aiscm_$(VERSION).orig.tar.gz
	tar xzf aiscm-$(VERSION).tar.gz -C pkg
	cp -a debian pkg/aiscm-$(VERSION)
	cd pkg/aiscm-$(VERSION) && debuild -us -uc -j4 && cd ../..
