(define-module (aiscm bool)
  #:use-module (oop goops)
  #:use-module (rnrs bytevectors)
  #:use-module (aiscm element)
  #:export (<bool>
            <meta<bool>>))
(define-class <meta<bool>> (<meta<element>>))
(define-class <bool> (<element>) #:metaclass <meta<bool>>)
(define-method (storage-size (self <meta<bool>>)) 1)
(define-method (pack (self <bool>))
  (u8-list->bytevector (list (if (get-value self) 1 0))))
(define-method (unpack (self <meta<bool>>) (packed <bytevector>))
  (make <bool> #:value (if (eq? (car (bytevector->u8-list packed)) 0) #f #t)))
(define-method (write (self <bool>) port)
  (format port "#<<bool> ~a>" (get-value self)))
(define-method (display (self <bool>) port)
  (format port "#<<bool> ~a>" (get-value self)))
(define-method (match (b <boolean>)) <bool>)
