(define-module (aiscm var)
  #:use-module (oop goops)
  #:use-module (aiscm element)
  #:export (<var>
            get-type))
(define-class <var> (<element>))
(define-method (subst (self <var>) alist)
  (if (assq self alist)
    (assq-ref alist self)
    self))
