(use-modules (oop goops) (aiscm v4l2) (aiscm sequence) (aiscm pointer) (aiscm jit) (aiscm rgb) (aiscm xorg) (aiscm util))
(define v (make <v4l2>))
(define img (to-array (grab v)))
(show (list (red img) (green img) (blue img)))
(destroy v)
