(use-modules (oop goops) (ice-9 rdelim) (aiscm v4l2) (aiscm util))
(define (select formats)
  (for-each (lambda (i mode) (format #t "~a: ~a~&" i mode))
            (iota (length formats))
            formats)
  ; (format #t "> ") (list-ref formats (string->number (read-line (current-input-port))))
  (list-ref formats 0))
(define v (make <v4l2> #:select select))
(grab v)
(destroy v)
