(use-modules (oop goops)
             (aiscm int)
             (aiscm asm)
             (aiscm jit)
             (guile-tap))
(define (subst cmd) (substitute-variables cmd (list (cons p RSP))))
(define p (var <long>))
(ok (equal? (MOV AX 0) (fix-stack-position (MOV AX 0) 123))
    "setting stack position does not affect operations not involving pointers")
(ok (equal? (MOV (ptr <byte> RSP 0) AL) (fix-stack-position (MOV (ptr <byte> stack-pointer 0) AL) 0))
    "setting stack position replaces the stack pointer placeholder with RSP")
(ok (equal? (MOV (ptr <byte> p) AL) (fix-stack-position (MOV (ptr <byte> p) AL) 0))
    "setting stack position ignores other pointer variables")
(ok (equal? (MOV (ptr <byte> RSP 123) AL) (fix-stack-position (MOV (ptr <byte> stack-pointer 0) AL) 123))
    "setting stack position takes the pointer offset into account")
(ok (equal? (MOV (ptr <byte> RSP 24) AL) (fix-stack-position (MOV (ptr <byte> stack-pointer 8) AL) 16))
    "stack pointer adjustment and pointer offset get added")
(ok (equal? (list (MOV (ptr <byte> RSP 0) AL)) (fix-stack-position (list (MOV (ptr <byte> stack-pointer 0) AL)) 0))
    "apply stack position adjustment to each command in a list")
(run-tests)
