(use-modules (oop goops)
             (aiscm element)
             (aiscm float)
             (guile-tap))
(planned-tests 6)
(ok (equal? (float single) (float single))
    "equality of classes")
(ok (eq? single (precision (float single)))
    "determine precision of single-precision floating point class")
(ok (eq? double (precision (float double)))
    "determine precision of double-precision floating point class")
(ok (equal? <float> (float single))
    "equality of predefined clases")
(ok (eqv? 4 (size-of <float>))
    "size of single-precision floating point number")
(ok (eqv? 8 (size-of <double>))
    "size of double-precision floating point number")
