(use-modules (aiscm int)
             (oop goops)
             (guile-tap))
(planned-tests 12)
;(ok (equal? (make-ubyte #x21) (make-usint #x21))
;  "equal integer objects")
(ok (not (equal? (make-ubyte #x21) (make-usint #x4321)))
  "unequal integer objects")
(ok (equal? 128 (bits (make-int-class 128 signed)))
  "integer class maintains number of bits")
(ok (signed? (make-int-class 128 signed))
  "integer class maintains signedness for signed integer")
(ok (not (signed? (make-int-class 128 unsigned)))
  "integer class maintains signedness for unsigned integer")
(ok (equal? #vu8(#xff) (pack (make-ubyte #xff)))
  "pack unsigned byte value")
(ok (equal? #vu8(#x01 #x02) (pack (make-usint #x0201)))
  "pack unsigned short integer value")
(ok (equal? #vu8(#x01 #x02 #x03 #x04) (pack (make-uint #x04030201)))
  "pack unsigned integer value")
(ok (equal? (unpack <ubyte> #vu8(#xff)) (make-ubyte #xff))
  "unpack unsigned byte value")
(ok (equal? (unpack <usint> #vu8(#x01 #x02)) (make-usint #x0201))
  "unpack unsigned short integer value")
(ok (equal? (unpack <uint> #vu8(#x01 #x02 #x03 #x04)) (make-uint #x04030201))
  "unpack unsigned integer value")
(ok (equal? 127 (slot-ref (unpack <byte> (pack (make-byte 127))) 'value))
  "pack and unpack signed byte")
(ok (equal? -128 (slot-ref (unpack <byte> (pack (make-byte -128))) 'value))
  "pack and unpack signed byte with negative number")
(format #t "~&")
