(use-modules (aiscm bool)
             (oop goops)
             (unit-test))
(define bool-false (make-bool #f))
(define bool-true (make-bool #t))
(define-class <test-bool> (<test-case>))
(define-method (test-equal (self <test-bool>))
  (assert-true (equal? (make-bool #f) (make-bool #f))))
(define-method (test-not-equal (self <test-bool>))
  (assert-true (not (equal? (make-bool #t) (make-bool #f)))))
(define-method (test-pack-false (self <test-bool>))
  (assert-equal #vu8(0) (pack bool-false)))
(define-method (test-pack-true (self <test-bool>))
  (assert-equal #vu8(1) (pack bool-true)))
(define-method (test-unpack-false (self <test-bool>))
  (assert-equal bool-false (unpack <bool> #vu8(0))))
(define-method (test-unpack-true (self <test-bool>))
  (assert-equal bool-true (unpack <bool> #vu8(1))))
(exit-with-summary (run-all-defined-test-cases))
