(use-modules (aiscm element)
             (aiscm malloc)
             (aiscm int)
             (aiscm var)
             (aiscm pointer)
             (aiscm lookup)
             (aiscm lambda)
             (oop goops)
             (guile-tap))
(planned-tests 8)
(define m (make-malloc 8))
(write-bytes m #vu8(1 2 3 4 5 6 7 8))
(define p (make-pointer <ubyte> m))
(define v (make-var))
(define l (make-lookup p v 1 8))
(define s (make-lambda v l))
(ok (equal? (get-value s) l)
  "query term of lambda")
(ok (equal? (get-index s) v)
  "query index variable of lambda")
(ok (equal? 3 (get s 2))
  "apply lambda by passing integer")
(ok (equal? 9 (begin (set s 3 9) (get s 3)))
  "write value to array and read it back")
(ok (equal? 9 (set s 3 9))
  "write value returns input value")
(ok (equal? <ubyte> (typecode s))
  "query element type of lambda")
(ok (eqv? 8 (size s))
  "query size of lambda")
(ok (equal? '(8) (shape s))
  "query shape of lambda")
(format #t "~&")
