(use-modules (oop goops)
             (aiscm int)
             (aiscm pulse)
             (guile-tap))
(ok (not (throws? (check-audio-sample-type <sint> <sint>)))
    "accept equal audio sample types")
(ok (throws? (check-audio-sample-type <sint> <ubyte>))
    "error if audio sample types do not match")
(ok (not (throws? (check-audio-sample-shape '(100) 1)))
    "check one-dimensional audio sample")
(ok (throws? (check-audio-sample-shape '(100) 2))
    "one-dimensional audio sample only works with one audio channel")
(ok (not (throws? (check-audio-sample-shape '(2 100) 2)))
    "check two-dimensional audio sample")
(ok (throws? (check-audio-sample-shape '(3 100) 2))
    "first dimension of 2D array must match number of channels")
(ok (throws? (check-audio-sample-shape '(2 2 100) 3))
    "audio sample array must not have more than 2 dimensions")
(ok (eqv? PA_SAMPLE_U8 (type->pulse-type <ubyte>))
    "convert unsigned byte to Pulse audio type")
(ok (eqv? PA_SAMPLE_S16LE (type->pulse-type <sint>))
    "convert short integer to Pulse audio type")
(ok (eqv? PA_SAMPLE_S32LE (type->pulse-type <int>))
    "convert integer to Pulse audio type")
(ok (eq? <sint> (pulse-type->type PA_SAMPLE_S16LE))
    "convert Pulse audio short integer to integer type")
(ok (throws? (type->pulse-type <usint>))
    "throw error if type not supported by Pulse audio")
(run-tests)
