(use-modules (guile-tap))
;(use-modules (guile-tap)
;             (aiscm malloc)
;             (oop goops))
(planned-tests 2)
(diagnostic "Testing")
(ok (= 1 1) "Pass")
(ok (= 1 2) "Failing")
(format #t "~&")
;(display "\n")
;(display "1..1\n")
;(display "ok 1 - Yes\n")
