(use-modules (aiscm bool)
             (oop goops)
             (unit-test))
(define bf (make-bool #f))
(define bt (make-bool #t))
(define-class <test-bool> (<test-case>))
(define-method (test-equal (self <test-bool>))
  (assert-true (equal? (make-bool #f) (make-bool #f))))
(define-method (test-not-equal (self <test-bool>))
  (assert-true (not (equal? (make-bool #t) (make-bool #f)))))
(define-method (test-pack-false (self <test-bool>))
  (assert-equal #vu8(0) (pack bf)))
(define-method (test-pack-true (self <test-bool>))
  (assert-equal #vu8(1) (pack bt)))
(define-method (test-unpack-false (self <test-bool>))
  (assert-equal bf (unpack-bool #vu8(0))))
(exit-with-summary (run-all-defined-test-cases))
