(use-modules (oop goops)
             (rnrs bytevectors)
             (system foreign)
             (aiscm frame)
             (guile-tap))
(define data (bytevector->pointer #vu8(2 3 5 7 11 13 17 19)))
(define f (make <frame> #:format 'GRAY #:width 8 #:height 1 #:data data))
(planned-tests 3)
(ok (equal? #vu8(2 2 2 255 3 3 3 255) (pointer->bytevector (get-data (convert f 'BGRA)) 8))
  "conversion to BGRA")
(ok (equal? 16 (get-width (convert f 'BGRA 16 2)))
  "width of scaled image")
(ok (equal? 2 (get-height (convert f 'BGRA 16 2)))
  "height of scaled image")
