(use-modules (oop goops)
             (aiscm int)
             (aiscm float)
             (aiscm pulse)
             (guile-tap))
(ok (eqv? PA_SAMPLE_U8 (type->pulse-type <ubyte>))
    "convert unsigned byte to Pulse audio type")
(ok (eqv? PA_SAMPLE_S16LE (type->pulse-type <sint>))
    "convert short integer to Pulse audio type")
(ok (eqv? PA_SAMPLE_S32LE (type->pulse-type <int>))
    "convert integer to Pulse audio type")
(ok (eqv? PA_SAMPLE_FLOAT32LE (type->pulse-type <float>))
    "convert floating-point to Pulse audio type")
(ok (throws? (type->pulse-type <usint>))
    "throw error if type not supported by Pulse audio")
(ok (eq? <sint> (pulse-type->type PA_SAMPLE_S16LE))
    "convert Pulse audio short integer to integer type")
(run-tests)
