(use-modules (aiscm magick)
             (aiscm element)
             (aiscm pointer)
             (aiscm sequence)
             (aiscm image)
             (aiscm rgb)
             (guile-tap))
(planned-tests 8)
(define ramp (read-image "fixtures/ramp.png"))
(define index (read-image "fixtures/index.png"))
(ok (equal? '(6 4) (shape ramp))
    "Check size of loaded image")
(ok (equal? (rgb 2 1 128) (get ramp 2 1))
    "Check pixel of loaded RGB image")
(ok (throws? (read-image "fixtures/nonexistent.png"))
    "Throw exception if file not found")
(ok (equal? 18 (get index 2 1))
    "Check pixel of loaded greyscale image")
(define grey-file-name (format #f "~a.png" (tmpnam)))
(define grey-values '((1 2 3) (4 5 6)))
(define grey-img (to-array grey-values))
(define retval (write-image grey-img grey-file-name))
(ok (eq? retval grey-img)
    "Writing image should return input image")
(define grey (read-image grey-file-name))
(ok (equal? grey-values (to-list grey))
    "Check content of saved greyscale image")
(ok (throws? (write-image grey-img "fixtures/nosuchdir/tmp.png"))
    "Should handle errors when writing image")
(define colour-file-name (format #f "~a.png" (tmpnam)))
(define colour-values (make-list 2 (make-list 8 (rgb 2 3 5))))
(define colour-img (to-array colour-values))
(write-image colour-img colour-file-name)
(define colour (read-image colour-file-name))
(ok (equal? colour-values (to-list colour))
    "Check content of saved colour image")
