(use-modules (oop goops)
             (aiscm element)
             (aiscm pointer)
             (aiscm malloc)
             (aiscm bool)
             (aiscm int)
             (guile-tap))
(planned-tests 3)
(define m (make-malloc 4))
(write-bytes m #vu8(1 2 3 4))
(ok (equal? (make-bool #t) (fetch (make-pointer <bool> m))))
(ok (equal? (make-byte 1) (fetch (make-pointer <byte> m))))
(ok (equal? (make-sint #x0201) (fetch (make-pointer <sint> m))))
(format #t "~&")
