(use-modules (aiscm int)
             (oop goops)
             (unit-test))
(define-class <test-int> (<test-case>))
(define-method (test-make-int-class-bits (self <test-int>))
  (assert-equal 21 (bits (make-int-class 21 signed))))
(define-method (test-make-int-class-signed (self <test-int>))
  (assert-true (signed? (make-int-class 21 signed))))
(define-method (test-make-int-class-not-signed (self <test-int>))
  (assert-true (not (signed? (make-int-class 21 unsigned)))))
(exit-with-summary (run-all-defined-test-cases))
