(use-modules (aiscm compile)
             (guile-tap))
(planned-tests 4)
(ok (equal? '(i 2) (expr->params '(+ i 2)))
    "get parameters of '(+ i 2)")
(ok (equal? '(i j k) (expr->params '(+ i (* j k))))
    "get parameters of '(+ i (* j k))")
(ok (equal? '<+_?_?> (expr->descr '(+ i 2)))
    "get descriptor of '(+ i 2)")
(ok (equal? '<+_?_<*_?_?>> (expr->descr '(+ i (* j k))))
    "get descriptor of '(+ i (* j k))")
(format #t "~&")
