(use-modules (aiscm element)
             (aiscm lookup)
             (aiscm malloc)
             (aiscm pointer)
             (aiscm var)
             (aiscm int)
             (oop goops)
             (guile-tap))
(define m (make-malloc 8))
(define p (make-pointer <byte> m))
(define v (make-var))
(define l (make-lookup p v 2 4))
(planned-tests 7)
(ok (equal? p (get-value l))
  "query value of lookup object")
(ok (eq? v (get-offset l))
  "query offset of lookup object")
(ok (eqv? 2 (get-stride l))
  "query stride of lookup object")
(ok (eqv? 4 (get-length l))
  "query length of lookup object")
(ok (equal? l (lookup p v 2 4))
  "lookup with variable")
(ok (equal? (+ p 2) (subst l (list (cons v 1))))
  "substituting variable in a lookup object")
(ok (eqv? 4 (dimension l v))
  "get dimension for variable in use")
(format #t "~&")
