(use-modules (guile-tap))

(load-extension "libguile-aiscm-tests" "init_tests")

(ok (ringbuffer-fetch-empty)
    "Fetching from empty ring buffer should return no data")
(ok (ringbuffer-initial-size)
    "Ring buffer initial size is as specified")
(ok (ringbuffer-add-data)
    "Adding data to ring buffer sets fill")
(ok (ringbuffer-store-and-fetch)
    "Ring buffer should allow fetching stored data")
(ok (ringbuffer-store-appends-data)
    "Adding more data to ring buffer appends to it")
(ok (ringbuffer-fetch-limit)
    "Do not fetch more than the specified number of bytes")
(ok (ringbuffer-fetching-advances)
    "Fetching from ring buffer advances it")
(ok (ringbuffer-storing-respects-offset)
    "Storing to ring buffer should be aware of offset")
(ok (ringbuffer-wrap-around)
    "Ring buffer should wrap around")
(ok (ringbuffer-grow)
    "Ringbuffer should grow n size if required")
(ok (ringbuffer-wrap-write)
    "Ringbuffer writing should wrap around")
(ok (ringbuffer-flushing)
    "Flushing ring buffer should empty it")
(run-tests)

