(use-modules (oop goops)
             (srfi srfi-1)
             (srfi srfi-26)
             (srfi srfi-64)
             (aiscm element)
             (aiscm int)
             (aiscm sequence)
             (aiscm util)
             (aiscm asm)
             (aiscm jit)
             (aiscm tensor))

(test-begin "playground")

(test-end "playground")
