(use-modules (oop goops) (aiscm ffmpeg) (aiscm xorg) (aiscm pulse) (aiscm util) (aiscm element) (aiscm image))
; https://www.youtube.com/watch?v=cGgf_dbDMsw
(define video (open-ffmpeg-input "av-sync.mp4"))
(define pulse (make <pulse-play> #:rate (rate video) #:channels (channels video) #:type (typecode video)))
(define time (clock))
(define x (/ 5 (frame-rate video)))
(show
  (lambda (dsp)
    ;(while (< (audio-pts video) (+ (video-pts video) (/ 1 2)))
    ;  (write-samples (read-audio video) pulse))
    (while (< (audio-pts video) x)
      (write-samples (read-audio video) pulse))
    (set! x (+ x (/ 1 (frame-rate video))))
    (format #t "~8,2f ~8,2f ~8,2f~&" (latency pulse) (exact->inexact (video-pts video)) (exact->inexact (audio-pts video)))
    (synchronise (read-video video) time (video-pts video) (event-loop dsp))))
(drain pulse)
