(use-modules (aiscm magick) (aiscm image) (aiscm core) (aiscm filters))
(define img (to-array (convert-image (to-image (read-image "star-ferry.jpg")) 'GRAY)))
(define b (gauss-filter 2.0 7))
(define bx (reshape b '(1 7)))
(define by (reshape b '(7 1)))
(define g (gauss-gradient-filter 2.0 7))
(define gx (reshape g '(1 7)))
(define gy (reshape g '(7 1)))
(define (gradient-x img) (convolve (convolve img gx) by))
(define (gradient-y img) (convolve (convolve img bx) gy))
(define (norm x y) (sqrt (+ (* x x) (* y y))))
(write-image (to-type <ubyte> (norm (gradient-x img) (gradient-y img))) "gauss-gradient.jpg")
