(use-modules (aiscm magick) (aiscm image) (aiscm core) (aiscm filters))
(define img (to-array (convert-image (to-image (read-image "star-ferry.jpg")) 'GRAY)))
(define x (gauss-gradient-x img 1.0))
(define y (gauss-gradient-y img 1.0))
(define a (gauss-blur (* x x) 1.0))
(define b (gauss-blur (* y y) 1.0))
(define c (gauss-blur (* x y) 1.0))
(define trace (+ a b))
(define determinant (- (* a b) (* c c)))
(define result (- determinant (* trace trace 0.05)))
(write-image (to-type <ubyte> (major (minor (+ (/ result 1000) 127) 255) 0)) "harris-stephens.jpg")
