(use-modules (oop goops) (aiscm magick) (aiscm core) (aiscm image))
(define colors (to-array (map (lambda (i) (rgb (max 0 (- 255 (abs (- (* i 4) (* 1 64 4)))))
                                               (max 0 (- 255 (abs (- (* i 4) (* 2 64 4)))))
                                               (max 0 (- 255 (abs (- (* i 4) (* 3 64 4)))))))
                              (iota 256))))
(define img (read-image "star-ferry.jpg"))
(write-image (warp colors (to-array (convert-image (to-image img) 'GRAY))) "pseudo.jpg")
