(use-modules (oop goops) (aiscm util) (aiscm pulse) (aiscm int) (aiscm pointer) (aiscm sequence))
(define samples (to-array <sint> (map (lambda (t) (round (* (sin (/ (* t 1000 2 3.1415926) 44100)) 20000))) (iota 441))))
(define play (make <pulse> #:type <sint> #:channels 1 #:rate 44100))
(for-each (lambda _ (write-samples samples play)) (iota 10))
(sleep 3)
(destroy play)
