(use-modules (oop goops)
             (ice-9 textual-ports)
             (ice-9 readline)
             (ice-9 format)
             (srfi srfi-1)
             (aiscm core)
             (aiscm ffmpeg)
             (aiscm tensorflow)
             (aiscm util)
             (aiscm tensors))

(define chunk 512)
(define input (open-ffmpeg-input "voice-commands.mp3"))
(define csv (open-file "voice-commands.csv" "r"))
(get-line csv)
(define features '())
(define words '())
(while #t
  (let [(line (get-line csv))]
    (if (eof-object? line) (break))
    (let* [(row     (string-split line #\,))
           (l       (string->number (car row)))
           (word    (cadr row))
           (samples (reshape (to-array (read-audio input (* chunk l))) (list l chunk)))]
      (set! features (cons samples features))
      (set! words (cons word words)))))
