@node Introduction
@chapter Introduction

@c @itemize
@c @item Item 1
@c @item Item 2
@c @end itemize

@menu
* Requirements::
* Installation::
* Testing::
@end menu

@node Requirements
@section Requirements

You need to install @uref{http://www.gnu.org/software/guile/,Guile} and its
development headers.

@example
sudo aptitude install guile-2.0 guile-2.0-dev
@end example

@noindent
You can also install the Guile documentation.

@example
sudo aptitude install guile-2.0-doc
@end example

@node Installation
@section Installation

You can install AIscm from an archive as follows:

@example
wget https://github.com/wedesoft/aiscm/releases/download/v@value{VERSION}/aiscm-@value{VERSION}.tar.xz
tar xf aiscm-@value{VERSION}.tar.xz
cd aiscm-@value{VERSION}
./configure
make
sudo make install
@end example

@node Testing
@section Testing

After installing AIscm you can run the test suite like this:

@example
make check
@end example

@c @noindent
@c Some Scheme example:
@c 
@c @lisp
@c (+ 1 2)
@c @result{} 3
@c (display 1)
@c @print{} 1
@c @end lisp
