name: AIscm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-24-04
    container:
      image: ubuntu:24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install depdendencies
      run: |
        apt -y update
        apt-get install -q -y build-essential
        apt-get install -q -y autoconf automake libtool
        apt-get install -q -y linux-libc-dev
        apt-get install -q -y guile-3.0-dev
        apt-get install -q -y libx11-dev libxext-dev libxv-dev libxmu-dev libxi-dev libglu1-mesa-dev libgl1-mesa-dev
        apt-get install -q -y gettext
        apt-get install -q -y pandoc
        apt-get install -q -y libjpeg-dev libmjpegtools-dev
        apt-get install -q -y libpulse-dev
        apt-get install -q -y imagemagick libmagickcore-dev
        apt-get install -q -y libxpm-dev
        apt-get install -q -y llvm-19 llvm-19-dev
        apt-get install -q -y clang-19 libomp5-19 libomp-19-dev
        apt-get install -q -y clearsilver-dev
        apt-get install -q -y protobuf-c-compiler libprotobuf-c-dev
        apt-get install -q -y cmake
        apt-get install -q -y wget
    - name: Install ffmpeg-4.4.6
      run: |
        wget https://www.ffmpeg.org/releases/ffmpeg-4.4.6.tar.xz
        tar -xf ffmpeg-4.4.6.tar.xz
        cd ffmpeg-4.4.6
        ./configure
        make
        make install
    - name: Install libtensorflow-cpu-linux
      run: |
        wget -q https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz
        tar xz -C /usr -f libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz
    - name: autoreconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: check
      run: make check
    - name: distributable
      run: make dist-xz
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: aiscm-source
        path: aiscm-*.tar.xz
