name: AIscm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install depdendencies
      run: |
        apt -y update
        apt -y install autoconf build-essential git
    - name: autoreconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: check
      run: make check
    - name: distributable
      run: make dist-xz
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: aiscm-source
        path: aiscm-*.tar.xz
